# 数据库必配
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/ivanmall_wms?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

# MapperScan
# sql映射文件位置 xml位置
# classpath 等价于 main/java + main/resources + 第三方jar包的根目录
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 11000
